### ISSUE TITLE
Unable to create converter

### ISSUE THREAD

**Issue by yaroslavzghoba** [google-developer-training/basic-android-kotlin-compose-training-mars-photos#107]
At the end of [step 8 of the "Get data from the internet" codelab](https://developer.android.com/codelabs/basic-android-kotlin-compose-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-5-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-getting-data-internet#7), when trying to run the application, we get the following exception:

java.lang.IllegalArgumentException: Unable to create converter for java.util.List<com.example.marsphotos.network.MarsPhoto> for method MarsApiService.getPhotos

Everything starts to work fine if you **change the version of the 'kotlinx.serialization' plugin added in the same step from 1.8.10 to 1.9.10** as done in the following codelabs.

**Comment by peterMonteer** [comment]
Yeah I think the problem is that it doesn't match the plugin _"    id("org.jetbrains.kotlin.android") version "1.9.10" apply false"_ declared at project level. 

The solutions seem to be:

Add the serialization plugin at project and applevel with the version you want to use
Match the serialization plugin version with the kotlin.android plugin version
